AsimAbbasWork/Repo2

fe_1.txt
final merging feature 1 work to develop branch
=> merging feature 1 development to develop branch

fe_2.txt
Feature_2 Branch is Margin in Develop Branch
=> Fe_2 Branch

fe_3.txt
Branch Feature 3 is merge in develop branch
=> This is Feature branch 3

fe_4.txt
This feature 4 branch merge in develop branch
=> This is feature 4 Branch

fe_5.txt
Feature_ branch merge in Develop Branch
=> This is feature_5 branch

fe_6.txt
Feature 6 branch merge in develop branch
=> This is feature 6 branch

fe_7.txt
feature 7 branch merge in develop branch
=> This is feature 7 branch

dev2_feature_1.txt
=> Dev2 feature4

fe_8.txt
This feature 8 branch merge into develop branch
=> This is feature 8 branch

fe_9.txt
this feature 9 branch merge into develop branch
=> This is feature 9 branch

ticket_1.txt
Merge feature 1 with  new ticket
=> This is new Ticket

ticket_2.txt
Feature 2 branch merge in develop branch with new ticket
=> This is new ticket_2

ticket_3.txt
feature 3 merge in develop branch with new ticket
=> This is new ticket_3

ticket_4.txt
feature 4 branch merge in develop branch with new ticket
=> This is new ticket_4

ticket_1.txt, ticket_2.txt, ticket_3.txt, ticket_5.txt
feature 5 branch merge in develop branch with new ticket
=> This is new ticket_5

ticket_6.txt
feature 6 branch merge in develop branch with new ticket
=> This is new ticket_6

ticket_7.txt
feature 7 branch merge in develop branch with new ticket
=> This is new ticket_7

ticket_8.txt
feature 8 branch merge in develop branch with new ticket
=> This is new ticket_8

ticket_9.txt
feature 9 branch merge in develop branch with new ticket
=> This is new ticket_9

fe_11.txt
feature 10 branch merge in develop branch
=> This is feature 11 branch

fe_10.txt, fe_11.txt
feature 10 branch merge into develop branch
=> This is feature 10 branch

fe_12.txt
feature 12 branch merge in develop branch
=> This is feature 12 branch

fe_13.txt
feature 13 branch merge in develop branch
=> This is feature 13 branch

fe_14.txt
feature 14 branch merge in develop branch
=> This is feature 14 branch

fe_15.txt
feature 15 branch merge in develop branch
=> This is feature 15 branch

fe_16.txt
feature 16 branch merge in develop branch
=> this is feature 16 branch

fe_17.txt
feature 17 branch merge in develop branch
=> this is feature 17 branch

fe_18.txt
feature 18 branch merge in develop branch
=> this is feature 18 branch

dev2_feature_2.txt, fe_10.txt, fe_11.txt, fe_12.txt, fe_13.txt, fe_14.txt, fe_15.txt, fe_16.txt, fe_17.txt, fe_18.txt, fe_9.txt, ticket_1.txt, ticket_2.txt, ticket_3.txt, ticket_4.txt, ticket_5.txt, ticket_6.txt, ticket_7.txt, ticket_8.txt, ticket_9.txt
commit for dev2_feature2 branch for scenario 5 of first sprint
=> Dev2 feature2

dex2_feat_3.txt
commit for dev2_feature3 branch for scenario 5 of first sprint
=> commit for feature 3 branch for scenario 5 of sprint 1

dev2_feat_5.txt
commit for dev2_feature5 branch for scenario 5 of first sprint
=> commit for dev2_feature5 branch for scenario 5 of first sprint

dev2_feat_6.txt
commit for dev2_feature6 branch for scenario 5 of first sprint
=> commit for dev2_feature6 branch for scenario 5 of first sprint

dev2_feat7.txt
commit for dev2_feature7 branch for scenario 5 of first sprint
=> commit for dev2_feature7 branch for scenario 5 of first sprint

dev2_feat_8.txt
"commit for dev2_feature8 branch for scenario 5 of first sprint"
=> commit for dev2_feature8 branch for scenario 5 of first sprint

dev2_feat_9.txt
"commit for dev2_feature9 branch for scenario 5 of first sprint end of first sprint all stories completed and  current stage is in testing of code before final release "
=> commit for dev2_feature9 branch for scenario 5 of first sprint

dev2_feat10.txt
commit for dev2_feature10 branch for scenario 8 of second sprint
=> commit for dev2_feature10 branch for scenario 8 of second sprint

dev2_feat12.txt
commit for dev2_feature12 branch for scenario 10 of second sprint
=> commit for dev2_feature12 branch for scenario 10 of second sprint

dev2_feat_14.txt
"commit for dev2_feature14 branch for scenario 10 of second sprint"
=> commit for dev2_feature14 branch for scenario 10 of second sprint

dev2_feat_15.txt
"commit for dev2_feature15 branch for scenario 10 of second sprint"
=> commit for dev2_feature15 branch for scenario 10 of second sprint

dev2_feat_16.txt
"commit for dev2_feature16 branch for scenario 10 of second sprint"
=> commit for dev2_feature16 branch for scenario 10 of second sprint

dev2_feat_17.txt
"commit for dev2_feature17 branch for scenario 10 of second sprint"
=> commit for dev2_feature17 branch for scenario 10 of second sprint

dev2_feat_18.txt
"Sprint All stories are completed and  code is in testing cycle at develop branch "
=> commit for dev2_feature18 branch for scenario 10 of second sprint
